name: "Preintegration Checks"
on:
  pull_request:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: "Check Android Project"
        run: './gradlew clean check assemble'

      - name: "Check Gradle Plugin Project"
        run: './gradlew -p include-build clean check jar'