name: "Create release"
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  release:
    runs-on: [ self-hosted-org, linux ]
    container:
      image: docker://docker.tuenti.io/android/novum_android:8
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Release library and plugin
        env:
          MOBILE_MAVENCENTRAL_USER: ${{ secrets.MOBILE_MAVENCENTRAL_USER }}
          MOBILE_MAVENCENTRAL_PASSWORD: ${{ secrets.MOBILE_MAVENCENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
        run: |
          ./gradlew clean publishReleasePublicationToSonatypeRepository -DLIBRARY_VERSION=0.0.1 --max-workers 1 closeAndReleaseStagingRepository
          ./gradlew -p include-build clean publishGradlePluginPublicationToSonatypeRepository -DLIBRARY_VERSION=0.0.1 --max-workers 1 closeAndReleaseStagingRepository