name: "Create release"
on:
  release:
    types: [published]
jobs:
  library:
    runs-on: [ self-hosted-org, linux ]
    container:
      image: docker://docker.tuenti.io/android/novum_android:8
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Release library
        env:
          MOBILE_MAVENCENTRAL_USER: ${{ secrets.MOBILE_MAVENCENTRAL_USER }}
          MOBILE_MAVENCENTRAL_PASSWORD: ${{ secrets.MOBILE_MAVENCENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
        run: |
          ./gradlew publishReleasePublicationToSonatypeRepository -DLIBRARY_VERSION=${{ github.event.release.tag_name }} --max-workers 1 closeAndReleaseStagingRepository
  plugin:
    runs-on: [ self-hosted-org, linux ]
    container:
      image: docker://docker.tuenti.io/android/novum_android:8
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Release plugin
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: |
          cd include-build
          ../gradlew publishPlugins -DLIBRARY_VERSION=${{ github.event.release.tag_name }}